### PR TITLE
pass sys_poll() return value on to libpd_poll_gui() caller

### PR DESCRIPTION
**Pull request by millerpuckette**

### CODE REVIEW

**Comment by danomatika** [comment]
Does this require a new version of Pd?

**Comment by millerpuckette** [comment]
It goes back at least to 0.48, probably further.

cheers
M

**Comment by millerpuckette** [comment]
P.S. I'm working on 0.51-3, which will probably be worth pulling into libpd
when it's solid.

**Comment by danomatika** [comment]
Ok, cool.

**Pull request merged**
