### PR TITLE
expose double-precision access

### PR DESCRIPTION
**Pull request by umlaeute**
i somehow lost my handle to PR #277 (so i think it's easiest to just reboot this PR from a new clone).

here's the initial description:
> this PR adds `double` variants for number-handling.
> 
> for discussion about #276

and some more:
> reviewer wishlist: @danomatika & @nettoyeurny
> the code has not been tested in real-world.
> it looks trivial enough, but the devil never sleeps...

PR updated to 541ad5ec6d74779172dbeffadfb05041827e7ecd (aka today's `master`)

### CODE REVIEW

**Comment by danomatika** [comment]
Could reading/writing doubles to a float array have potential overruns? Maybe not if it's all through a t_float?

This also makes me wonder if there should also be a define or function to check if libpd is using floats or double.

**Comment by danomatika** [comment]
I'm planning on releasing libpd 0.12 once Pd 0.51-3 is finalized as a stable release. I think it makes sense to merge this after so people can try it out for a while.

**Comment by umlaeute** [comment]
> Could reading/writing doubles to a float array have potential overruns? Maybe not if it's all through a `t_float` internally?

right. we don't do any `memcpy`-like copying, but instead copy the arrays element-by-element, so there shouldn't be any issues.

there's room for optimization here (if `sizeof(t_word)==sizeof(targetfloat)` we could use a proper `memcpy`), but that would need to be evaluated against the code generated by a modern C-compiler first.


> I'm planning on releasing libpd 0.12 once Pd 0.51-3 is finalized as a stable release

cool. i'd like to update https://github.com/pure-data/pure-data/pull/519 ;-)

>  I think it makes sense to merge this after so people can try it out for a while.

but then: maybe only after that....

**Comment by danomatika** [comment]
libpd 0.12 is almost done. There are some issues with the Python wrapper (2 vs 3) then it’s ready.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
> There are some issues with the Python wrapper (2 vs 3) then it’s ready.

sidenote: i think the default should by Python3 (Python2 has seen EOL almost a year ago, and it's getting increasingly harder to get it - and rightly so)

https://github.com/libpd/libpd/blob/0880cbf9a575c926894d48957e9a170f9dc2e4d0/python/Makefile#L1-L2

**Comment by danomatika** [comment]
Ok, great. I only use Python now and then. It would be easier just to update all syntax for Python 3 and be done with it.

**Comment by umlaeute** [comment]
any news on this?

**Comment by danomatika** [comment]
We are working on integrating #282. Once the multi instance stuff is working (including #343), this PR could be updated and we could add a double-precision C test project.

**Comment by danomatika** [comment]
I'm just going to take this for now. The multi-instance stuff is a bit more complicated and I would rather put out a new libpd version first with this included, then has the other stuff out later.

**Pull request merged**
