### PR TITLE
Android.mk: declare libpd_wrapper headers before outdated pure-data ones

### LINKED ISSUE #356: Android.mk missing update for double precision?
[Updating](https://github.com/libpd/pd-for-android/pull/122) pd-for-android to the latest commit is failing to build:
```
In file included from /home/runner/work/pd-for-android/pd-for-android/PdCore/src/main/jni/libpd/libpd_wrapper/util/z_queued.c:11:
/home/runner/work/pd-for-android/pd-for-android/PdCore/src/main/jni/libpd/libpd_wrapper/util/z_queued.h:43:47: error: unknown type name 't_libpd_doublehook'
EXTERN void libpd_set_queued_doublehook(const t_libpd_doublehook hook);
```

Any clues @danomatika ?

### PR DESCRIPTION
**Pull request by Ant1r**
This is untested, but there is a chance that  it could fix #356.

### CODE REVIEW

**Comment by joebowbeer** [comment]
Thanks @Ant1r. I'll add a GH workflow to build this.

**Comment by tkirshboim** [comment]
I cherry picked the commit from this branch on top of the libpd master branch and tried to build `pd-for-android` locally with it ([this branch](https://github.com/tkirshboim/pd-for-android/tree/tk-patch-2)). Compilation unfortunately still fails, with different compile errors:
```
/pd-for-android/PdCore/src/main/jni/libpd/jni/opensl_stream/opensl_stream.c:98:3: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
  clock_gettime(CLOCK_MONOTONIC, &t);
  ^
/pd-for-android/PdCore/src/main/jni/libpd/jni/opensl_stream/opensl_stream.c:510:3: warning: implicit declaration of function 'usleep' is invalid in C99 [-Wimplicit-function-declaration]
[x86] Compile        : pdnativeopensl <= opensl_stream.c
  usleep(100000);
make: Leaving directory '/pd-for-android/PdCore/src/main/jni'
  ^
2 warnings generated.
```

**Comment by Ant1r** [comment]
Looks like opensl_stream needs an update: 
``` C
#include <time.h>
```
is needed here (in place of sys/time.h).

**Comment by Ant1r** [comment]
Also needed (for usleep ()):
```
#include <unistd.h>
```

**Pull request merged**
