### PR TITLE
Fix crash libpd_openfile due to lock

### PR DESCRIPTION
**Pull request by pierreguillot**
It seems that `libpd_openfile()` needs to lock the global pd's mutex for writing otherwise because `glob_evalfile()` uses static variable and if several instances call this function it crashes.

### CODE REVIEW

**Comment by danomatika** [comment]
Thanks for checking this. Do we need *both* sys_lock and the globallock? I don't know, just checking.

**Comment by pierreguillot** [comment]
Yes because `sys_lock()` lock the instance and enables `pd_this->pd_islocked = 1;` then `globallock()` checks this value `if (!pd_this->pd_islocked) bug("pd_globallock");`

**Comment by pierreguillot** [comment]
I can also add my [test](https://github.com/pierreguillot/libpd/blob/dev/threadable/samples/c/pdtest_thread/pdtest_thread.c) (samples/c/pdtest_thread) from this [branch](https://github.com/pierreguillot/libpd/tree/dev/threadable) but it's a bit dirty for the moment

**Comment by danomatika** [comment]
Adding a test is a good idea. I recently cleaned up the makefiles so they they should be easy to adapt. The plan in the future is to update libpd to use auto tools.

**Comment by danomatika** [comment]
Looks good. Let me know when you feel the PR is ready. I'm thinking we will also provide a libpd wrapper for `pd_instance` such as `libpd_set_instance` or something similar.

**Comment by pierreguillot** [comment]
I think it's ready for this PR. Sorry for the slowness :)

**Comment by danomatika** [comment]
If you use the current master branch, you could update the test to use the "libpd_*_instance" functions. Also, the main Makefile now as a "MULTI" build option so you no longer need to set PDINSTANCE and DTHREADS in the test Makefile. Build libpd with multiple instance support via: `make MULTI=true`.

**Comment by pierreguillot** [comment]
Done ! Thanks

**Pull request merged**
