### PR TITLE
Set number format to "C" on pd_init().

### PR DESCRIPTION
**Pull request by residuum**
Fixes issue #130

### CODE REVIEW

**Comment by danomatika** [comment]
Maybe this should be a define, in case you need to turn if off? I think it should be on by default. Perhaps something like LIBPD_NO_LOCALE? pinging @nettoyeurny

**Comment by nettoyeurny** [comment]
I agree that there should be a way to turn this off. Not sure whether it should be on by default --- do we know how it interacts with iOS or Android?

**Comment by residuum** [comment]
OK, I have switched to using a define.

**Comment by danomatika** [comment]
This looks good.

One thing I can think of is making the define name less generic. As it applies only to libpd itself, how about `LIBPD_SETLOCALE` or `LIBPD_SET_LOCALE`? This would fit in with the existing `LIBPD_EXTRA`.

**Comment by danomatika** [comment]
This is now merged and I added info to the readme. Make variable is "SETLOCALE" and define is "LIBPD_LOCALE".

**Comment by danomatika** [comment]
Note: Based on #180, I decided to change the default to set LC_NUMERIC. There is info in the readme about this and the compiler define is now "LIBPD_NO_LOCALE" as it is now used to negate this default.

**Pull request merged**
