### PR TITLE
Update version for C# dll and NuGet

### PR DESCRIPTION
**Pull request by residuum**
Please merge this before tagging 0.11, but not earlier.

### CODE REVIEW

**Comment by danomatika** [comment]
Does this changeling summary make sense? https://github.com/libpd/libpd/blob/master/CHANGES.txt#L35

**Comment by danomatika** [comment]
I updated the README with info on setting up Msys2 & MinGW for building the csharplib on Windows. Can you check it out? I'm able to build both in 32 as well as 64 bit on Windows 10, although I've not tested the dlls.

**Comment by danomatika** [comment]
Also, should we mark the original LibPDBinding as deprecated?

**Comment by residuum** [comment]
> I updated the README with info on setting up Msys2 & MinGW for building the csharplib on Windows. Can you check it out? I'm able to build both in 32 as well as 64 bit on Windows 10, although I've not tested the dlls.

Yes, the library can be loaded and unit tests pass on Windows 8.1 with 32 and 64 bit code.

> Also, should we mark the original LibPDBinding as deprecated?

Good idea. With the update of the wrapper to multiinstance support, this will be better, and better warn people early enough. Should I add another PR or should I push to this one?

**Comment by danomatika** [comment]
You can push here.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Is this ready to merge?

**Comment by residuum** [comment]
This is ready to merge, yes.

**Comment by danomatika** [comment]
Bam

**Pull request merged**
