### PR TITLE
Add log level function

### PR DESCRIPTION
**Pull request by pierreguillot**
This PR adds to function in the C wrapper to change the loglevel (sys_verbose) - see #217.

### CODE REVIEW

**Comment by danomatika** [comment]
A couple changes:

* renamed to libpd_set_verbose()/libpd_get_verbose() to reflect what it actually controls
* keep sys_verbose = 0 in init, call libpd_set_verbose() after calling libpd_init()
* make sure set int is used as a bool

**Comment by pierreguillot** [comment]
- if verbose is init in `libpd_init()`, you can't have the verbose option activated while intialization. I thought that global variable like sys_verbose is init to 0 by default with C? Perhaps there can be another solution?
- sys_verbose is not a bool. Just `sys_verbose  > 0` would be better

**Comment by danomatika** [comment]
Ok fixed. Static ints are indeed inited to 0 in C.

**Comment by pierreguillot** [comment]
Great! Thanks!

**Pull request merged**
